In [1]:
import nltk
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all
       | 
       | Downloading package abc to /root/nltk_data...
       |   Unzipping corpora/abc.zip.
       | Downloading package alpino to /root/nltk_data...
       |   Unzipping corpora/alpino.zip.
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Unzipping corpora/biocreative_ppi.zip.
       | Downloading package brown to /root/nltk_data...
       |   Unzipping corpora/brown.zip.
       | Downloading package brown_tei to /root/nltk_data...
       |   Unzipping corpora/brown_tei.zip.
       | Downloading package cess_cat to /root/nltk_data...
       |   Unzipping corpora/cess_cat.zip.
       | Downloading package cess_esp to /root/nltk_data...
 

True

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from string import punctuation #Remove puntuationpunctuation 
from nltk.corpus import stopwords #Remove stop words
from nltk.tokenize import word_tokenize 
from nltk.stem import LancasterStemmer
from nltk.tag import pos_tag

In [3]:
data=pd.read_csv("/spam (1).csv",encoding='latin-1')

In [4]:
data=data.drop(['Unnamed: 2'	,'Unnamed: 3','Unnamed: 4'],axis=1)
data.columns = ['label', 'content']

In [5]:
from string import punctuation
from nltk.corpus import stopwords
stuff_to_be_removed = list(stopwords.words('english'))+list(punctuation)
from nltk.tokenize import word_tokenize
#from nltk.stem import LancasterStemmer
#stemmer = LancasterStemmer()
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmatizer = WordNetLemmatizer()
corpus = data['content'].tolist()
len(corpus)

5572

In [6]:
final_corpus = []
for i in range(len(corpus)):
  word = word_tokenize(corpus[i].lower())
  word = [lemmatizer.lemmatize(y) for y in word if y not in stuff_to_be_removed]
  j = " ".join(word)
  final_corpus.append(j)

In [7]:
final_corpus

['go jurong point crazy.. available bugis n great world la e buffet ... cine got amore wat ...',
 'ok lar ... joking wif u oni ...',
 "free entry 2 wkly comp win fa cup final tkts 21st may 2005. text fa 87121 receive entry question std txt rate c 's apply 08452810075over18 's",
 'u dun say early hor ... u c already say ...',
 "nah n't think go usf life around though",
 "freemsg hey darling 's 3 week 's word back 'd like fun still tb ok xxx std chgs send å£1.50 rcv",
 'even brother like speak treat like aid patent',
 "per request 'melle melle oru minnaminunginte nurungu vettam set callertune caller press *9 copy friend callertune",
 'winner valued network customer selected receivea å£900 prize reward claim call 09061701461. claim code kl341 valid 12 hour',
 'mobile 11 month u r entitled update latest colour mobile camera free call mobile update co free 08002986030',
 "'m gon na home soon n't want talk stuff anymore tonight k 've cried enough today",
 'six chance win cash 100 20,000 poun

In [8]:
label_list=data['label'].tolist()
df = pd.DataFrame(final_corpus)
df['label'] = label_list
df.columns=['content','label']

In [9]:
df

content label
0     go jurong point crazy.. available bugis n grea...   ham
1                       ok lar ... joking wif u oni ...   ham
2     free entry 2 wkly comp win fa cup final tkts 2...  spam
3           u dun say early hor ... u c already say ...   ham
4               nah n't think go usf life around though   ham
...                                                 ...   ...
5567  2nd time tried 2 contact u. u å£750 pound priz...  spam
5568                       ì_ b going esplanade fr home   ham
5569                           pity mood ... suggestion   ham
5570  guy bitching acted like 'd interested buying s...   ham
5571                                     rofl true name   ham

[5572 rows x 2 columns]

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
vector = tfidf.fit_transform(df['content'])
x_train = vector.toarray()
y_train= df['label']

In [11]:
from sklearn.naive_bayes import MultinomialNB
ab = MultinomialNB()
ab.fit(x_train,y_train)
ypred = ab.predict(x_train)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_train,ypred))
print(confusion_matrix(y_train,ypred))
print(classification_report(y_train,ypred))

0.9834888729361091
[[4825    0]
 [  92  655]]
              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      4825
        spam       1.00      0.88      0.93       747

    accuracy                           0.98      5572
   macro avg       0.99      0.94      0.96      5572
weighted avg       0.98      0.98      0.98      5572



In [12]:
from sklearn.naive_bayes import GaussianNB
ab = GaussianNB()
ab.fit(x_train,y_train)
ypred = ab.predict(x_train)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_train,ypred))
print(confusion_matrix(y_train,ypred))
print(classification_report(y_train,ypred))

0.9341349605168701
[[4458  367]
 [   0  747]]
              precision    recall  f1-score   support

         ham       1.00      0.92      0.96      4825
        spam       0.67      1.00      0.80       747

    accuracy                           0.93      5572
   macro avg       0.84      0.96      0.88      5572
weighted avg       0.96      0.93      0.94      5572



In [13]:
from xgboost import XGBClassifier
model = XGBClassifier(max_depth=10,random_state=1,learning_rate=0.05,seed=1)
model.fit(x_train, y_train)
y_pred=model.predict(x_train)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_train,ypred))
print(confusion_matrix(y_train,ypred))
print(classification_report(y_train,ypred))

0.9341349605168701
[[4458  367]
 [   0  747]]
              precision    recall  f1-score   support

         ham       1.00      0.92      0.96      4825
        spam       0.67      1.00      0.80       747

    accuracy                           0.93      5572
   macro avg       0.84      0.96      0.88      5572
weighted avg       0.96      0.93      0.94      5572

